version: '3.8'
services:
  fastapi-app:
    build: . 
    volumes:
      - .:/app
    env_file:
      - .env 
    ports:
      - "8001:8000"
    environment:
      - DATABASE_URL=postgresql://${APP_DB_USER}:${APP_DB_PASS}@db:5432/dbname
      - SECRET_KEY=test
      - ENV=test
    depends_on:
      - db
    networks:
      - account
      - kafka-network

  db:
    image: postgres:14 
    env_file:
      - .env 
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: db
    volumes:
      - ./db/01_init-db.sh:/docker-entrypoint-initdb.d/01_init-db.sh
      - ./db/02_init.sql:/docker-entrypoint-initdb.d/02_init-db.sql
      - ./db/03_final-db.sh:/docker-entrypoint-initdb.d/03_final-db.sh 
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432" 
    networks:
      - account
      - kafka-network

networks:
  account: 
  kafka-network:
    external: true

volumes:
  postgres_data:


