CREATE TABLE IF NOT EXISTS app.accounts (
    account_id SERIAL PRIMARY KEY,
    iban VARCHAR(34) UNIQUE NOT NULL,
    balance DECIMAL NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);
